### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by swa870** [lussier/etsmtl#12]
http://ets-horaire.krystosterone.com/

Le lien ne fonctionne plus.

**Comment by lussier** [comment]
Ok merci je vais l'enlever.

**Comment by dannytranlx** [comment]
On peut demander à @Krystosterone s'il le supporte encore!

**Comment by Krystosterone** [comment]
Le site est back up.

**Comment by lussier** [comment]
Cool, problem solved!

G.L.
